sed -e 's/,/ /g' IdLookupTable.csv > table.txt
sed -i s/left_eye_center_x/1/g table.txt
sed -i s/left_eye_center_y/2/g table.txt
sed -i s/right_eye_center_x/3/g table.txt
sed -i s/right_eye_center_y/4/g table.txt
sed -i s/left_eye_inner_corner_x/5/g table.txt
sed -i s/left_eye_inner_corner_y/6/g table.txt
sed -i s/left_eye_outer_corner_x/7/g table.txt
sed -i s/left_eye_outer_corner_y/8/g table.txt
sed -i s/right_eye_inner_corner_x/9/g table.txt
sed -i s/right_eye_inner_corner_y/10/g table.txt
sed -i s/right_eye_outer_corner_x/11/g table.txt
sed -i s/right_eye_outer_corner_y/12/g table.txt
sed -i s/left_eyebrow_inner_end_x/13/g table.txt
sed -i s/left_eyebrow_inner_end_y/14/g table.txt
sed -i s/left_eyebrow_outer_end_x/15/g table.txt
sed -i s/left_eyebrow_outer_end_y/16/g table.txt
sed -i s/right_eyebrow_inner_end_x/17/g table.txt
sed -i s/right_eyebrow_inner_end_y/18/g table.txt
sed -i s/right_eyebrow_outer_end_x/19/g table.txt
sed -i s/right_eyebrow_outer_end_y/20/g table.txt
sed -i s/nose_tip_x/21/g table.txt
sed -i s/nose_tip_y/22/g table.txt
sed -i s/mouth_left_corner_x/23/g table.txt
sed -i s/mouth_left_corner_y/24/g table.txt
sed -i s/mouth_right_corner_x/25/g table.txt
sed -i s/mouth_right_corner_y/26/g table.txt
sed -i s/mouth_center_top_lip_x/27/g table.txt
sed -i s/mouth_center_top_lip_y/28/g table.txt
sed -i s/mouth_center_bottom_lip_x/29/g table.txt
sed -i s/mouth_center_bottom_lip_y/30/g table.txt
